---
title: "w241 Final Project"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
```

```{r}
all <- read.csv("resp_improve.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
tail(all)
```




```{r}
filtered <- filter(
  all,
  wfh != "",
  wfh != "not_working",
  duration_focus_pre != "",
  duration_focus_post_2 != ""
)
nrow(all)
nrow(filtered)
```

```{r}
df <- data.frame(
  wfh = filtered$wfh,
  duration_focus_pre = filtered$duration_focus_pre,
  duration_focus_post = filtered$duration_focus_post_2
)
df
```

```{r}
control <- filter(df, wfh != "yes_post")
nrow(control)

treat <- filter(df, wfh == "yes_post")
nrow(treat)
```

```{r}
control
treat
```

```{r}
summary(control)
barplot(table(control$duration_focus_pre))
barplot(table(control$duration_focus_post))
```

```{r}
summary(treat)
barplot(table(treat$duration_focus_pre))
barplot(table(treat$duration_focus_post))
```

```{r}
library(data.table)
dt<-data.table(filtered)
dt[,treatment := 1*(wfh=='yes_post') + 0*(wfh=='no' | wfh=='yes_pre')]
dt[dt$wfh=='not_working',treatment :=NA]
table(dt$treatment,dt$wfh)
dt[,table(wfh)]

#covariate balance check
dt[,fisher.test(treatment,job_category)] #no significant association with job_category
dt$year<-as.numeric(levels(dt$year_of_birth))[dt$year_of_birth]
dt[,age := 2020-year]
dt[,t.test(age~treatment)] # no significant difference in age by treatment
dt[,fisher.test(treatment,sex)] # no significant association with sex
dt[,fisher.test(treatment,gender)] # no significant association with gender
dt[,fisher.test(treatment,race)] #no significant association with race
```
```{r}
#need to convert outcomes to numeric for analyses
all$new_duration_focus_pre<-plyr::mapvalues(all$duration_focus_pre, from = c("25% or less","Between 25% and 50%", "50% to 75%", "More than 75% of the time"), to = c(1,2,3,4)) %>% as.numeric()
all$new_duration_focus_post_2<-plyr::mapvalues(all$duration_focus_post_2, from = c( "Between 25% and 50%", "50% to 75%", "More than 75% of the time"), to = c(2,3,4)) %>% as.numeric()

how_often<-function(x) {plyr::mapvalues(x, from = c( "None of the time (0%)", "Some of the time (25%)", "Half the time (50%)", "Most of the time (75%)","All of the time (100%)"), to = c(0,1,2,3,4), warn_missing = FALSE) %>% as.numeric()}

all$how_often_anxiety<-how_often(all$how_often_anxiety)
all$how_often_coworker_problem<-how_often(all$how_often_coworker_problem)
all$how_often_low_energy<-how_often(all$how_often_low_energy)
all$how_often_poor_concentration<-how_often(all$how_often_poor_concentration)
all$how_often_less_work<-how_often(all$how_often_less_work)
all$how_often_poor_quality<-how_often(all$how_often_poor_quality)
all$how_often_more_mistakes<-how_often(all$how_often_more_mistakes)

#new hours of work
library(lubridate)
time_pre<-parse_date_time(all$time_start_pre, '%I:%M:%S %p')
time_post<-parse_date_time(all$time_start_post, '%I:%M:%S %p')
all$hours_work<-as.numeric(difftime(time_pre, time_post, units="mins"))


#attempting imputation by replacing missing with mean substitution
mice_all<-mice::mice(all, meth="mean")
new_all <- mice::complete(mice_all)

#new duration of focus
new_all$duration_focus <- new_all$new_duration_focus_pre - new_all$new_duration_focus_post_2
new_all$duration_focus


final<-data.table(new_all)
final[,treatment := 1*(wfh=='yes_post') + 0*(wfh=='no' | wfh=='yes_pre')]
final[wfh=='not_working',treatment :=NA]
table(final$wfh, final$treatment)
#work impairment
final$impairment <-final$how_often_low_energy+final$how_often_poor_concentration+final$how_often_anxiety+final$how_often_less_work+final$how_often_poor_quality+final$how_often_more_mistakes+final$how_often_coworker_problem

```

```{r}
#Analysis!
#Is there a significant difference in pre-post focus by treatment group?
final[,wilcox.test(duration_focus~treatment, exact=FALSE)]
final[,median(duration_focus), by=treatment]
#There is no significant difference in median pre-post focus by treatment group.

#Is there a significant difference in pre-post hours of work by treatment group?
#final[,wilcox.test(hours_work~treatment, exact=FALSE)] #don't use this
final[,mean(hours_work), by=treatment]
model<-final[,lm(hours_work~treatment)]
coeftest(model, vcov = vcovHC(model, type = "HC0"))

#There is no significant difference in mean pre-post hours of work by treatment group.

#Is there a significant difference in impairment between treatment and control (post-test only)?
model<-final[,lm(impairment~treatment)]
coeftest(model, vcov = vcovHC(model, type = "HC0"))
final[,mean(impairment), by=treatment]

```
